[package]
name = "actix-memory-example"
version = "0.1.0"
edition = "2021"

[dependencies]
multigear = { path = "../..", features = ["actix"] }
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }


