[package]
name = "custom-storage-example"
version = "0.1.0"
edition = "2021"

[dependencies]
multigear = { path = "../.." }
async-trait = "0.1"
bytes = "1"
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }


